# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: mlflowdb
    user: user
    secureJsonData:
      password: 'password'
    jsonData:
      sslmode: 'disable'
      database: mlflowdb

  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: monitoring
    user: monitoring_user
    secureJsonData:
      password: 'monitoring_password'
    jsonData:
      sslmode: 'disable'
      database: monitoring
