{
 "title": "Drifts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT \n  CAST(prediction_drift AS FLOAT) as prediction_drift, \n  _timestamp \nFROM monitoring.dummy_metrics "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT\n  _timestamp,\n  cast(share_missing_values as float) as share_missing_values\nFROM monitoring.dummy_metrics\n"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT \n  CAST(num_drifted_columns AS FLOAT) as num_drifted_columns, \n  _timestamp \nFROM monitoring.dummy_metrics\n"
    }
   ]
  }
 ]
}